{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kire-testing-app.backendName" . }}-config
  labels:
    {{- include "kire-testing-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        },
        "Console": {
          "FormatterName": "json",
          "FormatterOptions": {
            "SingleLine": true,
            "IncludeScopes": true,
            "TimestampFormat": "yyyy-MM-dd HH:mm:ss "
          }
        }
      },
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
          }
        },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog"
            }
          },
          {
            "Name": "File",
            "Args": {
              "path": "/var/log/kire-testing/application-.log",
              "rollingInterval": "Day",
              "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog"
            }
          }
        ],
        "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
        "Properties": {
          "Application": "KireTestingAPI",
          "Environment": "{{ .Values.global.environment }}"
        }
      },
      "AllowedHosts": "*"
    }
{{- end }}
