{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kire-testing-app.fullname" . }}-db-secret
  labels:
    {{- include "kire-testing-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.existingSecret }}
  # Use existing secret
  {{- else }}
  connection-string: {{ .Values.database.connectionString | b64enc | quote }}
  {{- end }}
{{- end }}
