name: Build and Deploy

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}/kire-testing-api
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/kire-testing-frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up .NET for backend
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/kire-testing-frontend/package-lock.json'      # Build and test backend
      - name: Build and test backend
        run: |
          cd backend/KireTestingAPI
          dotnet restore
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --configuration Release
      # Run OWASP dependency check
      - name: Run OWASP dependency check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'KireTestingAPI'
          path: 'backend/KireTestingAPI'
          format: 'HTML'
          out: 'reports'
          
      # Upload security report
      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports

      # Build frontend
      - name: Install frontend dependencies
        run: |
          cd frontend/kire-testing-frontend
          npm ci
        
      - name: Build frontend
        run: |
          cd frontend/kire-testing-frontend
          npm run build

      # Log in to the registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push Docker image for backend
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/KireTestingAPI/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}, ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Docker image for frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/kire-testing-frontend
          file: ./frontend/kire-testing-frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}, ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-helm-charts:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Helm chart versions
        run: |
          cd helm-charts/kire-testing-app
          sed -i "s/appVersion: .*$/appVersion: ${{ env.IMAGE_TAG }}/" Chart.yaml
          sed -i "s/tag: .*$/tag: ${{ env.IMAGE_TAG }}/" values.yaml

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push updated Helm charts
        run: |
          git add helm-charts/kire-testing-app/Chart.yaml helm-charts/kire-testing-app/values.yaml
          git commit -m "Update Helm charts for deployment ${{ env.IMAGE_TAG }}"
          git push

  deploy:
    needs: update-helm-charts
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    environment:
      name: ${{ github.event.inputs.deploy_environment }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64

      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Sync ArgoCD application
        run: |
          argocd app sync kire-testing-app-${{ github.event.inputs.deploy_environment }}
          argocd app wait kire-testing-app-${{ github.event.inputs.deploy_environment }} --health
